[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic_rag"
version = "0.1.0"
description = "Collection of agentic tools for code generation and retrieval augmented generation"
authors = [
  { name = "Your Name", email = "your_email@example.com" }
]
requires-python = "==3.11.11"
dependencies = [
  "typer>=0.9.0",
  "rich>=13.0.0",
  "questionary>=2.0.0",
  "langchain>=0.0.350",
  "langchain-community>=0.0.10",
  "langchain-huggingface==0.0.3",
  "langchain-core>=0.1.0",
  "chromadb>=0.4.0",
  "sentence-transformers>=2.2.0",
  "tiktoken>=0.5.0",
  "backoff>=2.2.0",
  "tenacity>=8.2.0",
  "datasets>=2.14.0",
  "transformers>=4.35.0",
  "openai>=1.0.0",
  "numpy>=1.24.0",
  "huggingface-hub>=0.19.0",
  "tokenizers>=0.15.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0",
  "black>=23.0.0",
  "ruff>=0.1.0"
]

[project.scripts]
agentic-rag = "agentic_rag.cli:app"

[tool.setuptools.packages.find]
where = ["src"]
include = ["agentic_rag*"]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF"]

[tool.black]
line-length = 120
target-version = ["py311"]
